name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: scikit-build/cmake-action@v2

    - name: Set up JUCE
      run: |
        git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release
      env:
        # Required for Windows to find MSBuild
        VCTargetsPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build
