name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: cmake/setup-cmake@v3
      with:
        cmake-version: '3.20'

    - name: Configure CMake
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-artifacts
        path: build/minimal_plugin_artefacts/Release

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: brew install cmake

    - name: Configure CMake
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Upload macOS Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-artifacts
        path: build/minimal_plugin_artefacts/Release

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Configure CMake
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-artifacts
        path: build/minimal_plugin_artefacts/Release
